version: "3.9"

services:
  app:
    build: .
    container_name: llm_app
    restart: always
    ports:
      - "8501:8501"
    env_file:
      - .env
    volumes:
      - chroma_data:/app/chroma_store
    networks:
      - llm-net

volumes:
  chroma_data:

networks:
  llm-net:
    external: true
